image: node:latest

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test
  - production

Build system:
  stage: build
  
  script:
    - echo "Installing dependencies..."
    - npm install
    - echo "Building..."
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 30 days

Code Linting:
  stage: test
  
  script:
    - echo "Code Linting...."
    - npm run lint

Deploy to production:
  stage: production
  
  script:
    - echo "Deploying to production server"
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
  
  rules:
    # We want to production as a manual step.
    - when: manual